package com.clau.gpt.annotation.autogeneratedunittest;

import org.springframework.stereotype.Component;

@Component
@GenerateUnitTest(
        appKey = "",
        endpoint = "",
        fileName = "CalculatorTest.java"
)
public class Calculator {

    @GenerateUnitTest(
            appKey = "",
            endpoint = "",
            fileName = "CalculatorTest.java"
    )
    public int add(int a, int b) {
        return a + b;
    }

    @GenerateUnitTest(
            appKey = "",
            endpoint = "",
            fileName = "CalculatorTest.java"
    )
    public int subtract(int a, int b) {
        return a - b;
    }
}
