package com.clau.gpt.annotation.autogeneratedunittest;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Target({ElementType.METHOD, ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
public @interface GenerateUnitTest {
    String appKey();
    String endpoint();
    String fileName();
}
