package com.clau.gpt.annotation.autogeneratedunittest.handler;

import com.clau.gpt.annotation.client.ChatGptClient;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.reflect.Method;

@Component
public class GenerateUnitTestHandler {

    @Autowired
    ChatGptClient chatGptClient;

    public void handle(String appKey, String endpoint, String fileName, Method method) throws IOException {
        // Generate the test method code for the given method
        // You can use a template or code generation library to make it easier.
        String testCode = generateTestMethodCode(appKey, endpoint, method);

        // Write the test code to the specified file
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileName, true))) {
            writer.write(testCode);
        }
    }

    private String generateTestMethodCode(String appKey, String endpoint, Method method) {
        // Generate the test method code for the given method
        // You can use a template or code generation library to make it easier.
        String res = chatGptClient.sendMessage(appKey, endpoint, method.toGenericString());
        return res; // Return the generated test method code here
    }
}
