package com.clau.gpt.AutoGeneratedComment;

public class ExampleClass {

    @AutoGeneratedComment
    public int performAction(String input) {
        // 实际逻辑
        return input.length();
    }
}

